# Generated by Django 3.1.7 on 2021-03-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
