# Generated by Django 3.1.7 on 2021-03-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210306_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('1', 'Automobile'), ('2', 'Books'), ('3', 'Electronics'), ('4', 'Collectibles'), ('5', 'Toys')], default='1', max_length=50),
        ),
    ]
