# Generated by Django 3.1.7 on 2021-03-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210307_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.URLField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/480px-No_image_available.svg.png', max_length=300, null=True),
        ),
    ]
