# Generated by Django 3.1.7 on 2021-03-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210307_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('1', 'Automobile'), ('2', 'Books'), ('3', 'Electronics'), ('4', 'Collectibles'), ('5', 'Toys')], default='1', max_length=50),
        ),
    ]
