# Generated by Django 3.1.7 on 2021-03-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210307_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('1', 'Automobile'), ('2', 'Books'), ('3', 'Electronics'), ('4', 'Collectibles'), ('5', 'Toys')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
