# Generated by Django 3.1.7 on 2021-03-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210307_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(choices=[('A', 'Automobile'), ('B', 'Books'), ('E', 'Electronics'), ('C', 'Collectibles'), ('T', 'Toys')], default='A', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
        ),
    ]
