# Generated by Django 3.1.7 on 2021-03-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210307_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listing',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('0', 'Categories'), ('1', 'Automobile'), ('2', 'Books'), ('3', 'Electronics'), ('4', 'Collectibles'), ('5', 'Toys')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='auctions.category'),
        ),
    ]
