# Generated by Django 3.1.7 on 2021-03-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210307_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingBid',
            new_name='currentPrice',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='currentBid',
        ),
    ]
